Feature/how it works parts2
IgorKonoval/goit-teamwork-14 pull request #15
Opened 2023-07-04 14:16 UTC by Resonanse-91

2023-07-04 15:08 UTC, IgorKonoval commented on src/css/how-it-works.css
>  .section-buying {
зачем это тут margin-left: 32px;?

2023-07-04 15:09 UTC, IgorKonoval approved these changes
у всех рисунков измени путь на ./
все цвета задай через var
text-shadow: 0px 4px 70px 0px rgba(0, 0, 0, 0.1); убери 0px перед rgba
удали заремареные правила
у тебя горизонтальный скрол - его не должно быть

2023-07-04 15:14 UTC, Resonanse-91 commented on src/css/how-it-works.css
>  .section-buying {
Если его убрать, то в мобильной версии, вся секция прижмётся к границе.

2023-07-04 21:55 UTC, IgorKonoval requested changes
Не пропустять. Контейнер повинен бути 335 кікселі і падінги по 20, а не приліпати до країв вікна. Треба перероблювати

цифри повинні бути по центру тексту, а в тебе приліплені до верху
та і дівчинка не по центру блоку
заголовок повинен бути h2
text-shadow: 0px 4px 70px 0px rgba(0, 0, 0, 0.1); треба прибрати 0px перед rgba

2023-07-05 20:26 UTC, IgorKonoval approved these changes

2023-07-05 20:36 UTC, merged