base-btn
IgorKonoval/goit-teamwork-14 pull request #5
Opened 2023-07-01 12:57 UTC by kssushas

2023-07-01 14:01 UTC, IgorKonoval requested changes
с кнопкой вроде все ровно, но не хватает стрелочки (надо Ваню поторопить) и какую-то анимашку прикольную можно прикрутить

2023-07-01 15:01 UTC, IgorKonoval requested changes
цікава анімашка. чекаю іконку на кнопку і можна заливати

2023-07-03 10:05 UTC, IgorKonoval commented on src/partials/vegetables.html
> +    <use href="../img/icons.svg#icon-vector-btn"></use>
./

2023-07-03 10:13 UTC, IgorKonoval commented on src/css/base.css
> +  --bg-hero: rgb(161, 196, 135);
цього робити не треба.
ти все одно не використовуєш його як var

2023-07-03 10:14 UTC, IgorKonoval commented on src/css/vegetables.css
>      color: #FFF;
задай через var

2023-07-03 10:14 UTC, IgorKonoval commented on src/css/vegetables.css
> + fill: #FFF;
задай через var

2023-07-03 10:16 UTC, IgorKonoval requested changes
@media screen and (min-width : 786px)
Переправ правило. Воно повинно бути 768

2023-07-03 10:49 UTC, kssushas commented on src/partials/vegetables.html
> +    <use href="../img/icons.svg#icon-vector-btn"></use>
якщо ./ , то так ми виходимо на папку "partials" , а папка імг ж ще на рівень вище))

2023-07-03 11:24 UTC, IgorKonoval approved these changes

2023-07-03 11:24 UTC, merged